@echo off
title FestaPDV - Preparando...
echo Criando a versao ultra-rapida do sistema...
echo Isso pode levar um ou dois minutos. Aguarde...
npm run build
echo.
echo PRONTO! O sistema agora esta otimizado para a festa.
pause
